name: Build and Test

on:
  workflow_dispatch: 
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: |
          cd HealthIndicators
          dotnet build --no-restore

      - name: Test
        run: |
          cd HealthIndicators
          dotnet test
        env:
          SQLConnectionString: ${{ secrets.SQLConnectionString }}