name: SonarQube

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Install SonarCloud Scanner
        run: |
          dotnet tool install --global dotnet-sonarscanner
        env:
          PATH: $PATH:/home/runner/.dotnet/tools

      - name: Run SonarCloud Begin Step
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          cd HealthIndicators
          dotnet sonarscanner begin /k:"sedar007_Z" /o:"sedar007" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.login="${{ secrets.SONAR_TOKEN }}" /d:sonar.cs.opencover.reportsPaths="TestResults/**/coverage.opencover.xml" /d:sonar.scanner.scanAll=false

      - name: Restore dependencies
        run: |
          cd HealthIndicators
          dotnet restore

      - name: Build
        run: |
          cd HealthIndicators
          dotnet build --no-restore

      - name: Run SonarCloud End Step
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          cd HealthIndicators
          dotnet sonarscanner end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"

      - name: Publish Test Results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: TestResults
          path: HealthIndicators/TestResults/**/*.trx
